package edu.training.web.controller.concrete;

public enum CommandName {
	DO_AUTH, DO_REGISTRATION,DO_LOGOUT,

	GO_TO_INDEX_PAGE, GO_TO_MAIN_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_SIGN_IN_PAGE,
	
	GO_TO_ADDING_PAGE,GO_TO_BUSINESS_PAGE,GO_TO_GOODNEWS_PAGE,
	
	SHOW_THE_WEATHER,

	NO_SUCH_COMMAND
}
